apiVersion: v1
kind: Service
metadata:
  name: pgpool-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: pgpool
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP