apiVersion: v1
kind: Service
metadata:
  name: postgres-slave
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: postgres
    role: slave
  ports:
    - port: {{ postgres_port | int }}
      targetPort: {{ postgres_port | int }}
