apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master
  namespace: default
spec:
  serviceName: "postgres-master"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: master
  template:
    metadata:
      labels:
        app: postgres
        role: master
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: postgres
          image: "docker.io/bitnami/postgresql:latest"
          env:
            - name: POSTGRESQL_USER
              value: "{{ db_username }}"
            - name: POSTGRESQL_PASSWORD
              value: "{{ db_password }}"
            - name: POSTGRESQL_DATABASE
              value: "{{ db_name }}"
            - name: POSTGRESQL_REPLICATION_MODE
              value: "master"
            - name: POSTGRESQL_REPLICATION_USER
              value: "repl_user"
            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: "repl_password"
          ports:
            - containerPort: {{ postgres_port | int }}
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgres-storage
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
        labels:
          app: postgres
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
